language: go

go:
  - "1.10.1"
  
services:
  - mysql
  
before_install:
  - cp go-crud/config.json go-crud/repo/config.json
  - sudo mysql < backup.sql
  - sudo mysql -e "use mysql; GRANT ALL PRIVILEGES ON *.* TO 'developer'@'localhost' IDENTIFIED BY '123';FLUSH PRIVILEGES;"
