version: '3.1'
services:  
  web:
    networks:
      - default-network
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    environment:
      GIN_MODE: release
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
  
  db:
    container_name: muve-db
    networks:
      - default-network
    build:
      context: .
      dockerfile: sql-server.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: XYZ_lakshan_dissanayake
      MYSQL_USER: developer
      MYSQL_PASSWORD: 123
    ports:
      - 3307:3306
    volumes:
      - "db-data:/var/lib/mysql"

volumes:
  db-data:

networks: 
  default-network:
